### ISSUE TITLE
Is it possible to build newest arm-adb from master branch ?

### ISSUE THREAD

**Issue by andrewleo** [hduong85/arm_adb#1]

**Comment by andrewleo** [comment]
maybe the 1.0.39 version

**Comment by qhuyduong** [comment]
Hi.

I'm working on implementing 1.0.39 version. Please wait.

Thanks.

**Comment by andrewleo** [comment]
Wonderful！
The master branch can provider "adb reconnect offline", it is very helpful to keep adb connection stable.
Waiting for your good news!!

**Comment by andrewleo** [comment]
By the way, how long may this take? :）

**Comment by qhuyduong** [comment]
Hi.

Please checkout branch v1.0.39. (No function tested). If there is any problem, please report to me.

Thanks.

**Comment by andrewleo** [comment]
Great, Thanks very much! I will follow the _README_ step by step.
By the way, can you upload the binary file to _Releases_ ? Maybe it is more convenient, especially for someone who do not have the build environment.

**Comment by qhuyduong** [comment]
Hi.
I just did the release. Please go and get it. :)

Thanks and best regards,
Huy Duong

**Comment by andrewleo** [comment]
I have download the binary, and it works well with some simple test !
I will perform sufficient testing on it next week, and report you the result.

**Comment by andrewleo** [comment]
By the way, I have follow _README_ to clone the code, and make on my raspberry pi 3B, but end up with following error:

```
../lib/libcrypto_utils/include/crypto_utils/android_pubkey.h:24:25: fatal error: openssl/rsa.h: No such file or directory
 #include <openssl/rsa.h>
                         ^
compilation terminated.
Makefile:605: recipe for target 'libcrypto_utils/libcrypto_utils_la-android_pubkey.lo' failed
make[2]: *** [libcrypto_utils/libcrypto_utils_la-android_pubkey.lo] Error 1
make[2]: Leaving directory '/root/adb-arm/arm_adb/lib'
Makefile:452: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/adb-arm/arm_adb'
Makefile:363: recipe for target 'all' failed
```

maybe I need some other source code from android framework ?

**Comment by qhuyduong** [comment]
Hi. 

Please try the following steps:

#### Native-compile openssl
```bash
$ git clone https://github.com/hduong85/openssl-1.0.2l.git
$ cd openssl-1.0.2l/
$ ./Configure --prefix=/tmp/openssl os/compiler:gcc
$ make && make install
$ cd -
```

#### Native-compile arm_adb
```bash
$ git clone https://github.com/hduong85/arm_adb
$ cd arm_adb
$ ./configure --includedir=/tmp/openssl/include --libdir=/tmp/openssl/lib
$ make
```

**Comment by andrewleo** [comment]
I will try it next week on my raspberry pi 3b, much thanks！

**Comment by andrewleo** [comment]
When I clone the v1.0.39 branch source code, and run the command, the following error occurs:
```
make[2]: Leaving directory '/root/adb-arm/arm_adb/lib'
Making all in src
make[2]: Entering directory '/root/adb-arm/arm_adb/src'
make[2]: *** No rule to make target 'adb.c', needed by 'adb-adb.o'.  Stop.
make[2]: Leaving directory '/root/adb-arm/arm_adb/src'
Makefile:452: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/adb-arm/arm_adb'
Makefile:363: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by andrewleo** [comment]
By the way, the default port of arm-adb server is 5038. I do not want to use -P 5037 or export ANDROID_ADB_SERVER_PORT=5037, how can I change to 5037 as default?

**Comment by andrewleo** [comment]
By change the source code in adb.h, 5038 to 5037, now make an _adb_ using 5037 as default. :）

**Comment by qhuyduong** [comment]
:+1: Good job buddy :)

**Comment by qhuyduong** [comment]
By the way, I will close this issue. Please open another if any :)
